"""
Django settings for bwdesignworld project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import sys
import os

reload(sys)
sys.setdefaultencoding('utf-8')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#Image sizes constants
ARTICLE_IMAGE_THUMB_PATH = 'article/article_thumb/'
ARTICLE_IMAGE_MEDIUM_PATH = 'article/article_medium_image/'
ARTICLE_IMAGE_LARGE_PATH = 'article/article_large_image/'
ARTICLE_IMAGE_EXTRA_LARGE_PATH = 'article/article_extra_large_image/'
PHOTOSHOOT_IMAGE_PATH = 'album/'
AUTHOR_IMAGE_PATH = 'author/'
EVENT_IMAGE_PATH = 'event/'
QUICKBYTES_IMAGE_THUMB_PATH = 'quickbyte/quickbytes_thumb/'
QUICKBYTES_IMAGE_MEDIUM_PATH = 'quickbyte/quickbytes_medium_image/'
#QUICKBYTES_IMAGE_LARGE_PATH = ''
QUICKBYTES_IMAGE_EXTRA_LARGE_PATH = 'quickbyte/quickbytes_extralarge_image/'
MAGAZINE_IMAGE_PATH_URL='magazineissue/'
EXPERT_IMAGE_PATHS = 'debate/expertimage/'
DEBATE_IMAGE_PATHS ='debate/featuredimage/'
FEATURED_BOX_IMAGE_PATH ='featurebox/'
FEATURED_BOX2_IMAGE_PATH ='featurebox2/'
FEATURED_BOX3_IMAGE_PATH ='featurebox3/'
VIDEO_MASTER ='videomain/'
VIDEO_THUMB ='mainvideothumb/'
QUOTES_IMAGE='quotesimage/'
BUCKET_PATH = ''
AWS_S3_BASE_URL = 'http://static.businessworld.in/'
#End

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bif@oj_c5=uhsv!eanv73w7-ej28^40k6l4jq@=t%93atozca7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['localhost'] #when debug is false
ALLOWED_HOSTS = ['*'] #when debug is true

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'haystack', #search
    'bwdesignworld',
    'homepage',
    'articles',
    'author',
    'category',
    'tags',
    'sponsored',
    'topics',
    'quotes',
    'libs',
    'quickbytes',
    'newsletter',
    'photoshoot',
    'businessentertainment',
    'columns',
    'community',
    'event',
    'magazineisuue',
    'mainnewsletter',
    'authornewslatter',
    'mainvideo'
)

MIDDLEWARE_CLASSES = (
    'django.middleware.gzip.GZipMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'bwdesignworld.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bwdesignworld.context_processors.global_settings',
            ]
        },
    },
]

#CACHE_BACKEND = 'memcached://127.0.0.1:11211/'

'''CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}'''

WSGI_APPLICATION = 'bwdesignworld.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bw_wellness_db',
        'USER': 'root',
        'PASSWORD': 'bwchannelsuser2016',
        'HOST': '104.199.166.236',
        'PORT': '3306',
        'CONN_MAX_AGE': 5,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_PATH = os.path.join(BASE_DIR, 'static')

#STATIC_ROOT = 'static' #when debug is false
STATIC_ROOT = 'staticfiles' #when debug is true

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    STATIC_PATH,
)

# haystack search using elasticsearch
AWS_ELASTICSEARCH_URL = 'http://search-bw-channels-w6amsfjrp7l42icj5pmzufh2im.ap-southeast-1.es.amazonaws.com/'
AWS_ELASTICSEARCH_INDEX = 'bw_hotelier_index/'

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'search-bw-channels-w6amsfjrp7l42icj5pmzufh2im.ap-southeast-1.es.amazonaws.com',
        'INDEX_NAME': 'haystack',
    },
}

# http://django-haystack.readthedocs.org/en/latest/signal_processors.html
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# increase the default number of results (from 20)
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 40